-- MySQL Script generated by MySQL Workbench
-- 04/15/19 10:29:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema glassesStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema glassesStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `glassesStore` DEFAULT CHARACTER SET utf8 ;
USE `glassesStore` ;

-- -----------------------------------------------------
-- Table `glassesStore`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `glassesStore`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `street` VARCHAR(50) NULL,
  `number` INT NULL,
  `floor` INT NULL,
  `door` INT NULL,
  `city` VARCHAR(50) NULL,
  `zipCode` VARCHAR(50) NULL,
  `country` VARCHAR(50) NULL,
  `phone` INT NULL,
  `fax` INT NULL,
  `NIF` VARCHAR(45) NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glassesStore`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `glassesStore`.`Glasses` (
  `idGlasses` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(50) NOT NULL,
  `prescription1` FLOAT NOT NULL,
  `prescription2` FLOAT NOT NULL,
  `frame` ENUM('floating', 'rimmed', 'metallic') NOT NULL,
  `colorFrame` VARCHAR(50) NOT NULL,
  `colorGlass1` VARCHAR(50) NOT NULL,
  `colorGlass2` VARCHAR(50) NOT NULL,
  `price` FLOAT NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  INDEX `fk_Glasses_Supplier1_idx` (`Supplier_idSupplier` ASC),
  CONSTRAINT `fk_Glasses_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `glassesStore`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `glassesStore`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `glassesStore`.`Clients` (
  `name` VARCHAR(50) NOT NULL,
  `street` VARCHAR(50) NULL,
  `number` INT NULL,
  `floor` INT NULL,
  `door` INT NULL,
  `city` VARCHAR(50) NULL,
  `zipCode` INT NULL,
  `country` VARCHAR(50) NULL,
  `phone` INT NULL,
  `email` VARCHAR(50) NULL,
  `dateRegister` DATE NULL,
  `attendedBy` VARCHAR(50) NULL,
  `recommendedBy` VARCHAR(50) NULL,
  `Glasses_idGlasses` INT NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_Clients_Glasses_idx` (`Glasses_idGlasses` ASC),
  CONSTRAINT `fk_Clients_Glasses`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `glassesStore`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
